WITH P AS (
    SELECT B.DR_NAME, B.DR_ID, B.LCNS_NO, A.APNT_YMD, A.APNT_NO, A.PT_NO, A.MCDP_CD, A.APNT_CNCL_YN
    FROM APPOINTMENT AS A
    JOIN DOCTOR AS B
    ON A.MDDR_ID = B.DR_ID
    WHERE A.APNT_YMD LIKE '2022-04-13%' AND A.APNT_CNCL_YN = 'N'
)

SELECT P.APNT_NO, A.PT_NAME, A.PT_NO, P.MCDP_CD, P.DR_NAME, P.APNT_YMD
FROM P
JOIN PATIENT AS A
ON P.PT_NO = A.PT_NO
ORDER BY P.APNT_YMD
