WITH A AS (
    SELECT I.ITEM_ID
    FROM ITEM_INFO AS I
    JOIN ITEM_TREE AS T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
)

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT * FROM A)
ORDER BY ITEM_ID DESC
