
EXTRACT(MONTH FROM START_DATE)
START_DATE BETWEEN DATE '2022-10-01' AND DATE '2022-11-01'
concat : ||
SUBSTR
--------------------------

SELECT *
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >=2
    )
ORDER BY ID

--------------------------

SELECT
    MONTH,
    CAR_ID,
    COUNT(*) AS RECORDS
FROM
(
    SELECT
        EXTRACT(MONTH FROM START_DATE) AS MONTH
        , CAR_ID
        , COUNT(*) OVER(PARTITION BY CAR_ID) AS RECORDS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
)
WHERE RECORDS >=5
GROUP BY
    MONTH
    , CAR_ID
ORDER BY 1, 2 DESC

--------------------------

SELECT
   '/home/grep/src/'|| A.BOARD_ID||'/'||B.FILE_ID||B.FILE_NAME||B.FILE_EXT AS FILE_PATH
FROM
(
    SELECT
        BOARD_ID
    ,   VIEWS
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    FETCH FIRST 1 ROWS ONLY
) A
LEFT JOIN USED_GOODS_FILE B
ON A.BOARD_ID = B.BOARD_ID
ORDER BY 1 DESC



SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A
RIGHT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
ORDER BY 1,2

--------------------------

SELECT
    B.USER_ID
    , B.NICKNAME
    , B.CITY || ' ' || B.STREET_ADDRESS1 || ' ' || B.STREET_ADDRESS2 AS "전체주소"
    , SUBSTR(TLNO,1,3) || '-' || SUBSTR(TLNO,4,4) || '-' || SUBSTR(TLNO,8,4) AS "전화번호"
FROM (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >=3
) A
JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
ORDER BY 1 DESC