SELECT /*+FULL(A) */
    A.CAR_ID
    , A.CAR_TYPE
    , A.DAILY_FEE * 30 * (100-C.DISCOUNT_RATE)/100 AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR A
    ,CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
WHERE A.CAR_TYPE = C.CAR_TYPE
    AND A.CAR_TYPE IN ('세단','SUV')
    AND C.DURATION_TYPE = '30일 이상'
    AND CAR_ID NOT IN
    (
        SELECT DISTINCT(CAR_ID)
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE (START_DATE <= DATE '2022-11-30' AND END_DATE >= DATE '2022-11-01')
    )
    AND A.DAILY_FEE * 30 * (100-C.DISCOUNT_RATE)/100 BETWEEN '500000' AND '1999999'
ORDER BY 3 DESC, 2,1 DESC

-------------------------------------------------------------------------------------

SELECT
    HISTORY_ID
    , DAILY_FEE * (C.END_DATE - C.START_DATE +1) * (100-NVL(D.DISCOUNT_RATE,0))/100 AS FEE
FROM
    (
    SELECT
        A.HISTORY_ID
        , A.CAR_ID
        , CASE WHEN END_DATE - START_DATE +1 >=90 THEN '90일 이상'
        WHEN END_DATE - START_DATE +1 >=30 THEN '30일 이상'
        WHEN END_DATE - START_DATE +1 >=7 THEN '7일 이상'
        ELSE NULL END AS DIFF_DATE
        , A.START_DATE
        , A.END_DATE
        , B.CAR_TYPE
        , B.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
       JOIN CAR_RENTAL_COMPANY_CAR B
        ON A.CAR_ID = B.CAR_ID
) C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
    AND C.DIFF_DATE = D.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC

-------------------------------------------------------------------------------------

SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Yogurt','Milk')
GROUP BY CART_ID
HAVING COUNT(DISTINCT(NAME)) >=2
ORDER BY 1

-------------------------------------------------------------------------------------

SELECT
    EXTRACT (YEAR FROM OS.SALES_DATE) AS YEAR
    , EXTRACT (MONTH FROM OS.SALES_DATE) AS MONTH
    , UI.GENDER
    , COUNT(DISTINCT(OS.USER_ID)) AS USERS
FROM USER_INFO UI
JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY
    EXTRACT (YEAR FROM OS.SALES_DATE)
    , EXTRACT (MONTH FROM OS.SALES_DATE)
    , UI.GENDER
ORDER BY 1,2,3
