WITH A AS (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS A
          FROM ECOLI_DATA
          GROUP BY YEAR)
# 내 풀이: 암묵적 조인 사용(구형 SQL 스타일)
# SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (A.A-E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
# FROM ECOLI_DATA E, A A
# WHERE YEAR(E.DIFFERENTIATION_DATE) = A.YEAR
# ORDER BY YEAR, YEAR_DEV;

# 추천 풀이: 명시적 JOIN 사용. 가독성과 유지보수에 더 유리함. 최신 SQL에서 권장.
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (A.A-E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN A ON YEAR(E.DIFFERENTIATION_DATE)=A.YEAR
ORDER BY YEAR, YEAR_DEV;
