SELECT ANIMAL_ID, NAME
FROM (
         SELECT AI.ANIMAL_ID, AI.NAME, AO.DATETIME - AI.DATETIME AS DIFFTIME
         FROM ANIMAL_INS AI,
              ANIMAL_OUTS AO
         WHERE AI.ANIMAL_ID = AO.ANIMAL_ID
         ORDER BY DIFFTIME DESC
     )
WHERE ROWNUM <=2
-- FETCH FIRST 2 ROWS ONLY