/*solve 1*/
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
   ,(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) B
WHERE A.FOOD_TYPE = B.FOOD_TYPE
  AND A.FAVORITES = B.FAVORITES
ORDER BY A.FOOD_TYPE DESC

/*solve 2*/
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
         SELECT FOOD_TYPE, FAVORITES, REST_ID, REST_NAME,
                ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANK
         FROM REST_INFO
     )
WHERE RANK = 1
ORDER BY FOOD_TYPE DESC

/*
ROW_NUMBER() : 1234
RANK() : 1224
DENSE_RANK() : 1223

ROW_NUMBER() OVER(PARTITION BY ~~ ORDER BY ~~) AS ~~
*/