-- SELECT
--     CAR_ID,
--     MAX(CASE
--     WHEN '2022-10-16' BETWEEN TO_CHAR(START_DATE,'YYYY-MM-DD')
--                       AND TO_CHAR(END_DATE,'YYYY-MM-DD') THEN '대여중'
--     ELSE '대여 가능'
--     END) AS AVAILABILITY
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- GROUP BY CAR_ID
-- ORDER BY CAR_ID DESC

SELECT
    CAR_ID,
    CASE WHEN
             SUM(
                     CASE WHEN '2022-10-16' BETWEEN TO_CHAR(START_DATE,'YYYY-MM-DD')
                         AND TO_CHAR(END_DATE,'YYYY-MM-DD') THEN 1
                          ELSE 0 END
             ) > 0 THEN '대여중'
         ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC