SELECT TO_NUMBER(TO_CHAR(START_DATE,'MM')) AS MONTH
    , CAR_ID
    , COUNT(*) AS RECORDS
FROM(
    SELECT H.*
        , COUNT(*) OVER(PARTITION BY CAR_ID) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE TO_CHAR(H.START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
    )
WHERE CNT >=5
GROUP BY CAR_ID, TO_CHAR(START_DATE,'MM')
ORDER BY TO_CHAR(START_DATE,'MM') , CAR_ID DESC