WITH A AS (SELECT COUNT(DISTINCT USER_ID) AS USERS
          FROM USER_INFO
          WHERE YEAR(JOINED)=2021
)
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
            ROUND(COUNT(DISTINCT O.USER_ID)/A.USERS,1) AS PURCHASED_RATIO
FROM ONLINE_SALE O, A, USER_INFO I
WHERE YEAR(I.JOINED)=2021 AND I.USER_ID=O.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
