WITH A AS(
    SELECT ID, EMAIL, GROUP_CONCAT(DISTINCT NAME, CATEGORY) AS GROUPED
    FROM SKILLCODES S
    JOIN DEVELOPERS D ON D.SKILL_CODE & S.CODE
    GROUP BY 1, 2
)

SELECT CASE
    WHEN GROUPED LIKE '%Front%' AND GROUPED LIKE '%Python%' THEN 'A'
    WHEN GROUPED LIKE '%C#%' THEN 'B'
    WHEN GROUPED LIKE '%Front%' THEN 'C'
    END AS GRADE,
    ID, EMAIL
FROM A
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;
