WITH RECURSIVE GENERATIONTREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION+1
    FROM ECOLI_DATA E
    JOIN GENERATIONTREE G ON G.ID=E.PARENT_ID
)

SELECT COUNT(G.ID) AS `COUNT`, G.GENERATION
FROM GENERATIONTREE G
LEFT JOIN ECOLI_DATA E ON E.PARENT_ID = G.ID
WHERE E.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION;
