WITH A AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM A
JOIN USED_GOODS_FILE F
ON A.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC
