WITH JOIN2021 AS (
    SELECT *
    FROM USER_INFO UI
    WHERE TO_CHAR(UI.JOINED, 'YYYY') = '2021'
),
     PURCHASECNT AS(
         SELECT
             TO_CHAR(OS.SALES_DATE,'YYYY') AS YEAR,
    TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM')) AS MONTH,
    COUNT(DISTINCT(OS.USER_ID)) AS PURCHASED_USERS
FROM ONLINE_SALE OS
    INNER JOIN JOIN2021 J2 ON OS.USER_ID = J2.USER_ID
GROUP BY
    TO_CHAR(OS.SALES_DATE,'YYYY'),
    TO_NUMBER(TO_CHAR(OS.SALES_DATE, 'MM'))
    )

SELECT YEAR,
    MONTH,
    PURCHASED_USERS,
    ROUND(PURCHASED_USERS / (SELECT COUNT(*) FROM JOIN2021),1) AS PUCHASED_RATIO
FROM PURCHASECNT
ORDER BY YEAR, MONTH