SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AI
         JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID=AO.ANIMAL_ID
WHERE NOT (AI.SEX_UPON_INTAKE LIKE 'Neutered%' OR AI.SEX_UPON_INTAKE LIKE 'Spayed%')
  AND (AO.SEX_UPON_OUTCOME LIKE 'Neutered%' OR AO.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME;