WITH A AS (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS R
    FROM ECOLI_DATA
)
SELECT ID, 
    CASE WHEN R >= 0.75 THEN "CRITICAL"
    WHEN R >= 0.5 THEN "HIGH"
    WHEN R >= 0.25 THEN "MEDIUM"
    ELSE "LOW"
    END AS COLONY_NAME
FROM A
ORDER BY ID

# PERCENT_RANK) 외우기!!
