WITH A AS (
    SELECT *
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE != "Spayed Female" AND SEX_UPON_INTAKE != "Neutered Male"
)

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS AS O
JOIN A
ON A.ANIMAL_ID = O.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME = "Spayed Female" OR O.SEX_UPON_OUTCOME = "Neutered Male"
ORDER BY O.ANIMAL_ID

