WITH CTE AS (
SELECT
    CRCRH. HISTORY_ID
    , CRCC.CAR_TYPE
    , CRCC.DAILY_FEE
    , CRCRH.END_DATE - CRCRH.START_DATE + 1 AS DIFF_DATE
FROM
    CAR_RENTAL_COMPANY_CAR CRCC
    , CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
WHERE 1=1
    AND CRCC.CAR_ID = CRCRH.CAR_ID
)

SELECT
    HISTORY_ID
    , DAILY_FEE * DIFF_DATE * (100 - NVL(REGEXP_REPLACE(CRCDP.DISCOUNT_RATE,'[^0-9]',''),0)) / 100 AS FEE
FROM
    CTE C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
    ON C.CAR_TYPE = CRCDP.CAR_TYPE
    AND
        CRCDP.DURATION_TYPE = (
        CASE WHEN C.DIFF_DATE >= 90 THEN '90일 이상'
            WHEN C.DIFF_DATE >= 30 THEN '30일 이상'
            WHEN C.DIFF_DATE >= 7 THEN '7일 이상'
            ELSE NULL END
        )
WHERE C.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC