SELECT
    DISTINCT(CRCC.CAR_ID)
    , CRCC.CAR_TYPE
    , CRCC.DAILY_FEE * 30 * (100-CRCDP.DISCOUNT_RATE) / 100 AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR CRCC
    , CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    , CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
WHERE 1=1
    AND CRCC.CAR_ID = CRCRH.CAR_ID
    AND CRCC.CAR_TYPE = CRCDP.CAR_TYPE
    AND CRCC.CAR_TYPE IN ('세단','SUV')
    AND CRCDP.DURATION_TYPE = '30일 이상'
    AND CRCC.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
        WHERE TO_CHAR(CRCRH.START_DATE ,'YYYYMMDD') <= '20221130'
            AND TO_CHAR(CRCRH.END_DATE ,'YYYYMMDD') >= '20221101'
        GROUP BY CAR_ID
    )
    AND CRCC.DAILY_FEE * 30 * (100-CRCDP.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2 , 1 DESC