SELECT
      B.MEMBER_NAME
      , C.REVIEW_TEXT
      , TO_CHAR(C.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM
(
    SELECT
        MEMBER_ID
        , CNT
        , RANK() OVER(ORDER BY CNT DESC) AS RANK
    FROM
    (
        SELECT
            MEMBER_ID
            , COUNT(*) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    )
    ORDER BY CNT DESC
    FETCH FIRST 1 ROWS ONLY
) A
JOIN MEMBER_PROFILE B
ON A.MEMBER_ID = B.MEMBER_ID
JOIN REST_REVIEW C
ON A.MEMBER_ID = C.MEMBER_ID
WHERE 1=1
    AND A.RANK = 1
ORDER BY 3,2
