SELECT
    CATEGORY
    , PRICE AS MAX_PRICE
    , PRODUCT_NAME
FROM (SELECT
    CATEGORY
    , ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANK
    , PRICE
    , PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
WHERE RANK = 1
ORDER BY PRICE DESC
