SELECT 
    R1.ID
    , R1.START_TIME
    , R1.END_TIME 
FROM RESERVATION R1
WHERE NOT EXISTS (
    SELECT 1
    FROM RESERVATION R2
    WHERE 1=1
        AND R1.ID > R2.ID
        AND R1.START_TIME < R2.END_TIME 
        AND R1.END_TIME > R2.START_TIME
)
ORDER BY R1.START_TIME 
