SELECT 
    RANKING AS NTH_SUBMISSION
    , ROUND(SUM(CHECKING) * 100 / COUNT(*),0) AS CORRECT_RATE 
FROM (
    SELECT 
        S.USER_ID
        , S.PROBLEM_ID
        , S.SUBMITTED
        , P.CORRECT_ANSWER 
        , CASE WHEN S.SUBMITTED = P.CORRECT_ANSWER THEN 1 ELSE 0 END AS CHECKING
        , S.TIMESTAMP
        , RANK() OVER (PARTITION BY S.USER_ID, S.PROBLEM_ID ORDER BY S.TIMESTAMP ASC) AS RANKING    
    FROM SUBMISSIONS S
    JOIN PROBLEMS P ON S.PROBLEM_ID = P.PROBLEM_ID 
)
GROUP BY RANKING 
ORDER BY 1 
