SELECT H.HOUR AS HOUR
    , COUNT(AO.ANIMAL_ID) AS COUNT
FROM
    (
        SELECT LEVEL -1 AS HOUR
        FROM DUAL
        CONNECT BY LEVEL <=24
    ) H
LEFT OUTER JOIN  ANIMAL_OUTS AO
ON H.HOUR = TO_NUMBER(TO_CHAR(AO.DATETIME, 'HH24'))
GROUP BY HOUR
ORDER BY 1

-- SELECT TO_CHAR(datetime, 'HH24:MI:SS') FROM 테이블명;
-- SELECT TO_CHAR(datetime, 'HH24') FROM 테이블명;
-- SELECT TO_CHAR(datetime, 'AM HH12:MI') FROM 테이블명;

-- SELECT LEVEL -1 AS HOUR
-- FROM DUAL
-- CONNECT BY LEVEL <=24