WITH RENT_DIFF AS (
SELECT
    CRCC.CAR_TYPE
    , CRCC.DAILY_FEE
    , CRCRH.HISTORY_ID
    , CRCRH.END_DATE - CRCRH.START_DATE +1 AS DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    JOIN CAR_RENTAL_COMPANY_CAR CRCC
    ON CRCRH.CAR_ID = CRCC.CAR_ID
WHERE 1=1
    AND CRCC.CAR_TYPE = '트럭'
)

SELECT
    RD.HISTORY_ID
    , FLOOR(RD.DURATION * RD.DAILY_FEE * (100-NVL(REGEXP_REPLACE(CRCDP.DISCOUNT_RATE,'[^0-9]',''),0)) / 100) AS FEE
FROM RENT_DIFF RD
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON RD.CAR_TYPE = CRCDP.CAR_TYPE
AND CRCDP.DURATION_TYPE = (
    CASE
        WHEN RD.DURATION >= 90 THEN '90일 이상'
        WHEN RD.DURATION >= 30 THEN '30일 이상'
        WHEN RD.DURATION >= 7 THEN '7일 이상'
        ELSE NULL
    END
)
ORDER BY FEE DESC , RD.HISTORY_ID DESC;