WITH RENTAL_INFO AS (
    SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE,
           DATEDIFF(H.END_DATE, H.START_DATE)+1 AS RENTAL_DAYS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
),
DISCOUNT_INFO AS (
    SELECT CAR_TYPE, 
           REGEXP_REPLACE(DURATION_TYPE, '[^0-9]+', '') AS DURATION_DAYS, 
           DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
)

SELECT R.HISTORY_ID,
       ROUND(R.DAILY_FEE*R.RENTAL_DAYS*(100-IFNULL(MAX(D.DISCOUNT_RATE),0))/100,0) AS FEE
       # ,R.RENTAL_DAYS, MAX(D.DURATION_DAYS), MAX(D.DISCOUNT_RATE)
FROM RENTAL_INFO R
LEFT JOIN DISCOUNT_INFO D ON R.CAR_TYPE = D.CAR_TYPE AND R.RENTAL_DAYS >= D.DURATION_DAYS
WHERE R.CAR_TYPE = '트럭'
GROUP BY R.HISTORY_ID, R.RENTAL_DAYS, R.DAILY_FEE
ORDER BY FEE DESC, R.HISTORY_ID DESC;

# CASE 구문이랑 MAX랑 같이 사용하면 제대로 값을 구하지 못함.
