WITH FILTERED_CARS AS ( SELECT CAR_ID, COUNT(*) AS TOTAL_RENTAL
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE START_DATE >= '2022-08-01' AND START_DATE<='2022-10-31'
                       GROUP BY CAR_ID
                       HAVING TOTAL_RENTAL>=5
),

RENTAL_INFO AS (SELECT MONTH(START_DATE) AS MONTH, CAR_ID, START_DATE
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
                WHERE START_DATE >= '2022-08-01' AND START_DATE<='2022-10-31'
                    AND CAR_ID IN (SELECT CAR_ID FROM FILTERED_CARS)
)

SELECT MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM RENTAL_INFO
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;

# 오답!!
# 이렇게 구하면 월별로 대여 횟수가 5이상인 경우만 결과값에 나옴.
# 기간 내에 5회 이상 대여하면 되는데, 내가 만든건 한 달에 5회 이상인 애들만 출력하도록 하고 있음.
# WITH A AS(SELECT MONTH(START_DATE) AS MONTH, CAR_ID, START_DATE
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE START_DATE >= '2022-08-01' AND START_DATE<='2022-10-31')

# SELECT MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM A
# GROUP BY MONTH, CAR_ID
# HAVING RECORDS>=5
# ORDER BY MONTH, CAR_ID DESC;
