select COUNT(*) as "FISH_COUNT" , MAX(LENGTH) AS "MAX_LENGTH", FISH_TYPE
from FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH,10)) >= 33 
ORDER BY FISH_TYPE ASC;

// *** IFNULL ** 
// AVG(IFNULL(LENGTH,10)) 
// 평균 구할때 LENGTH 값이 NULL 이면 10으로 처리해서 계산. 
