
SELECT I.ID AS ID, N.FISH_NAME AS FISH_NAME, IFNULL(I.LENGTH, 0) AS LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.FISH_TYPE IN ( SELECT FISH_TYPE
                    FROM FISH_INFO
                    GROUP BY FISH_TYPE
                    HAVING MAX(LENGTH) = LENGTH)
ORDER BY I.ID
