SELECT F.ITEM_ID, F.ITEM_NAME, F.RARITY
FROM ITEM_INFO F INNER JOIN ITEM_TREE T ON F.ITEM_ID=T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN
        (SELECT T.ITEM_ID
        FROM ITEM_INFO F INNER JOIN ITEM_TREE T ON F.ITEM_ID = T.ITEM_ID
        WHERE F.RARITY LIKE 'RARE')
ORDER BY F.ITEM_ID DESC;
