WITH RENTAL_COUNT AS (
    SELECT CAR_ID, COUNT(*) AS TOTAL_RENTALS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING TOTAL_RENTALS > 4
)

SELECT 
    MONTH(A.START_DATE) AS MONTH, 
    A.CAR_ID, 
    COUNT(A.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
JOIN RENTAL_COUNT B 
ON A.CAR_ID = B.CAR_ID
WHERE MONTH(A.START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH(A.START_DATE), A.CAR_ID
ORDER BY MONTH(A.START_DATE), A.CAR_ID DESC;
