SELECT
    A.HOUR,
    CASE WHEN AO.CNT IS NULL THEN 0
    ELSE AO.CNT
    END AS COUNT
FROM (
    SELECT LEVEL -1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) A
LEFT JOIN
(
    SELECT
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
    , COUNT(*) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
) AO
ON A.HOUR = AO.HOUR
ORDER BY A.HOUR
