SELECT
    CAR_ID
    , CAR_TYPE
    , FEE
FROM
(
    SELECT
        C.CAR_ID
        , C.CAR_TYPE
        , FLOOR(C.DAILY_FEE * 30 * (100-P.DISCOUNT_RATE)/100) AS FEE
    FROM
        CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
        ON C.CAR_TYPE = P.CAR_TYPE
    WHERE 1=1
        AND C.CAR_TYPE IN ('세단', 'SUV')
        AND P.DURATION_TYPE = '30일 이상'
        AND C.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE 1=1
                AND TO_CHAR(START_DATE ,'YYYY-MM-DD') <= '2022-11-30'
                AND TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-11-01'
        )
)
WHERE 1=1
    AND FEE BETWEEN 500000 AND 1999999
GROUP BY CAR_ID, CAR_TYPE, FEE
ORDER BY 3 DESC, 2 , 1 DESC


