SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM (SELECT FOOD_PRODUCT.*,
             ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANK
      FROM FOOD_PRODUCT) A
WHERE A.category IN ('과자', '국', '김치', '식용유')
  AND A.RANK = 1
ORDER BY A.PRICE DESC