SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
     , SUM(B.PRICE * BS.SALES)AS TOTAL_SALES
FROM BOOK B,
     AUTHOR A,
     BOOK_SALES BS
WHERE 1=1
  AND B.AUTHOR_ID = A.AUTHOR_ID
  AND B.BOOK_ID = BS.BOOK_ID
  AND TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC