SELECT
    TO_CHAR(OS.SALES_DATE, 'YYYY') AS YEAR
    , TO_NUMBER(TO_CHAR(OS.SALES_DATE,'MM')) AS MONTH
    , UI.GENDER
    , COUNT(DISTINCT(UI.USER_ID)) AS USERS
FROM USER_INFO UI
    , ONLINE_SALE OS
WHERE 1=1
    AND UI.USER_ID = OS.USER_ID
    AND UI.GENDER IS NOT NULL
GROUP BY
    TO_CHAR(OS.SALES_DATE, 'YYYY')
    , TO_NUMBER(TO_CHAR(OS.SALES_DATE,'MM'))
    , UI.GENDER
ORDER BY 1,2,3