-- INTERSECT
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Milk'
INTERSECT
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'Yogurt'
ORDER BY CART_ID

--HAVING
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT(NAME)) >=2
ORDER BY CART_ID

--LISTAGG
SELECT CART_ID
FROM (
    SELECT
        CART_ID
        , LISTAGG(NAME, ', ') AS NAME
    FROM CART_PRODUCTS
    GROUP BY CART_ID
)
WHERE 1=1
    AND NAME LIKE '%Milk%'
    AND NAME LIKE '%Yogurt%'
ORDER BY CART_ID