WITH ONEG AS (
    SELECT *
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
), 
SECG AS (
    SELECT E.ID, E.PARENT_ID
    FROM ECOLI_DATA E
    JOIN ONEG
    ON E.PARENT_ID = ONEG.ID
)

SELECT E.ID
FROM ECOLI_DATA E
JOIN SECG AS S
ON S.ID = E.PARENT_ID
ORDER BY E.ID
