WITH A AS (
    SELECT *
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%INTACT%'
)
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS AS O
JOIN A
ON A.ANIMAL_ID = O.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME NOT LIKE '%INTACT%'
