WITH A AS (
    SELECT MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, A.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F
JOIN A
ON A.PRICE = F.PRICE
WHERE F.CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY MAX_PRICE DESC

