SELECT
    HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM (
    SELECT LEVEL -1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) H
LEFT JOIN ANIMAL_OUTS AO
ON H.HOUR = TO_NUMBER(TO_CHAR(AO.DATETIME,'HH24'))
GROUP BY H.HOUR
ORDER BY HOUR;

