WITH CT AS (
    SELECT
        CRCC.CAR_TYPE
        , CRCC.DAILY_FEE
        , CRCRH.HISTORY_ID
        , CRCRH.END_DATE - CRCRH.START_DATE +1 AS DATEDIFF
    FROM
        CAR_RENTAL_COMPANY_CAR CRCC
        ,CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    WHERE 1=1
        AND CRCC.CAR_ID = CRCRH.CAR_ID
        AND CRCC.CAR_TYPE = '트럭'
)

SELECT
    CT.HISTORY_ID
    , FLOOR(CT.DAILY_FEE
        * CT.DATEDIFF
        * (100 - REGEXP_REPLACE(NVL(CRCDP.DISCOUNT_RATE,0),'[^0-9]')) / 100)
    AS FEE
FROM CT
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
    ON CT.CAR_TYPE = CRCDP.CAR_TYPE
    AND CRCDP.DURATION_TYPE = (
        CASE WHEN CT.DATEDIFF >= 90 THEN '90일 이상'
        WHEN CT.DATEDIFF >= 30 THEN '30일 이상'
        WHEN CT.DATEDIFF >= 7 THEN '7일 이상'
        ELSE NULL
        END
    )
ORDER BY 2 DESC, 1 DESC
