WITH CI AS (
    SELECT
        CRCR.CAR_ID
        , CRCR.DAILY_FEE
        , CRCR.CAR_TYPE
        , CRCDP.DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_CAR CRCR
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
        ON CRCR.CAR_TYPE = CRCDP.CAR_TYPE
    WHERE 1=1
        AND CRCR.CAR_TYPE IN ('세단','SUV')
        AND CRCDP.DURATION_TYPE = '30일 이상'
        AND CRCR.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
            WHERE TO_CHAR(CRCRH.START_DATE,'YYYYMMDD') <= '20221130'
                AND TO_CHAR(CRCRH.END_DATE, 'YYYYMMDD') >= '20221101'
        )
    )

SELECT
    CAR_ID
    , CAR_TYPE
    , FLOOR(DAILY_FEE *
            30 * (100-REGEXP_REPLACE(DISCOUNT_RATE,'[^0-9]'))/100) AS FEE
FROM CI
WHERE 1=1
    AND DAILY_FEE *
        30 * (100-REGEXP_REPLACE(DISCOUNT_RATE,'[^0-9]'))/100 BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2, 1 DESC


