WITH C AS (
    SELECT
        COUNT(*) AS CNT
    FROM USER_INFO
    WHERE TO_CHAR(JOINED,'YYYY') = '2021'
)

SELECT
    TO_CHAR(OS.SALES_DATE,'YYYY') AS YEAR
    , TO_NUMBER(TO_CHAR(OS.SALES_DATE,'MM')) AS MONTH
    , COUNT(DISTINCT(OS.USER_ID)) AS PURCHASED_USERS
    , ROUND(COUNT(DISTINCT(OS.USER_ID))/(SELECT CNT FROM C),1) AS PUCHASED_RATIO
FROM USER_INFO UI
    JOIN ONLINE_SALE OS
    ON UI.USER_ID = OS.USER_ID
WHERE 1=1
    AND TO_CHAR(UI.JOINED,'YYYY') = '2021'
GROUP BY
    TO_CHAR(OS.SALES_DATE,'YYYY')
    , TO_NUMBER(TO_CHAR(OS.SALES_DATE,'MM'))
ORDER BY 1,2
