SELECT  DISTINCT(CRCC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR CRCC
   ,CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
WHERE CRCC.CAR_ID = CRCRH.CAR_ID
  AND CRCC.CAR_TYPE = '세단'
  AND TO_CHAR(CRCRH.START_DATE,'MM') = '10'
ORDER BY CRCC.CAR_ID DESC
