/*01 ans*/
SELECT *
FROM
    (SELECT AI.NAME, AI.DATETIME
    FROM ANIMAL_INS AI
        LEFT OUTER JOIN ANIMAL_OUTS AO
        ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NULL
ORDER BY AI.DATETIME)
WHERE ROWNUM <=3

/*02 ans*/
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI
    LEFT OUTER JOIN ANIMAL_OUTS AO
        ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NULL
ORDER BY AI.DATETIME
FETCH FIRST 3 ROWS ONLY

/*
WHERE ROWNUM <=3
FETCH FIRST 3 ROWS ONLY
*/