SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
WHERE SKILL_CODE & (
SELECT SUM(CODE) FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'
)
ORDER BY ID

//다른풀이//
WITH FRONTEND_SKILLS AS (
  SELECT CODE
  FROM SKILLCODES
  WHERE CATEGORY = 'Front End'
)
SELECT DISTINCT ID, EMAIL, FRIST_NAME, LAST_NAME 
FROM DEVELOPERS
JOIN FRONTEND_SKILLS ON SKILL_CODE & CODE
ORDER BY ID;
