select concat('/home/grep/src/',B.board_ID,'/',B.file_id,B.FILE_NAME,B.FILE_EXT) as FILE_PATH
from USED_GOODS_BOARD as A,
USED_GOODS_FILE as B
WHERE A.BOARD_ID = B.BOARD_ID
AND A.VIEWS = (
SELECT MAX(A.VIEWS)
FROM USED_GOODS_BOARD AS A)
ORDER BY B.FILE_ID DESC;
