SELECT 
    CRCR.CAR_ID 
    , CRCR.CAR_TYPE 
    , CRCR.DAILY_FEE * 30 * (100- REGEXP_REPLACE(CRCDP.DISCOUNT_RATE, '[^0-9]','')) / 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCR,
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
WHERE CRCR.CAR_TYPE = CRCDP.CAR_TYPE 
    AND CRCR.CAR_TYPE IN ('세단','SUV')
    AND CRCDP.DURATION_TYPE = '30일 이상'
    AND CRCR.CAR_ID NOT IN (
        SELECT CAR_ID 
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
            WHERE TO_CHAR(START_DATE,'YYYYMMDD') <= '20221130'
            AND TO_CHAR(END_DATE,'YYYYMMDD') >= '20221101'
        )
    AND CRCR.DAILY_FEE * 30 * (100- REGEXP_REPLACE(CRCDP.DISCOUNT_RATE, '[^0-9]','')) / 100 BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2 , 1 DESC
